plugins {
    id 'org.relativitymc.neo-loom' version '1.16.+' apply false
}

subprojects {
    if (!it.name.startsWith('datapack')) {
        apply plugin: 'idea'
        apply plugin: 'java'
        apply plugin: 'java-library'
        apply plugin: 'maven-publish'
        apply plugin: 'org.relativitymc.neo-loom'

        project.base.archivesName = "${rootProject.archives_base_name}-${project.name}"
    }
}

tasks.register('build') {
    group = "build"
}

subprojects {
    if (!it.name.startsWith('datapack')) {
        group = rootProject.maven_group
        version = rootProject.mod_version

        java.toolchain.languageVersion = JavaLanguageVersion.of(project.java_version)

        repositories {
            mavenLocal()
            mavenCentral()
            maven {
                name = 'TerraformersMC'
                url = 'https://maven.terraformersmc.com/'
            }
        }

        dependencies {
            minecraft "com.mojang:minecraft:${project.minecraft_version}"
        }

        // Hack to allow calling build via root project
        rootProject.tasks.build.dependsOn(it.tasks.build)

        jar {
            from(rootProject.file('LICENSE'))
        }

        tasks.withType(JavaCompile).configureEach {
            it.options.encoding = 'UTF-8'
            it.options.getRelease().set(25)
        }

        idea {
            module {
                downloadSources = true
                downloadJavadoc = true
            }
        }

        // Configuration that applies to all subprojects except :common
        if (it.name != "common") {
            configurations {
                commonJava {
                    canBeResolved = true
                }
                commonResources {
                    canBeResolved = true
                }
            }

            dependencies {
                compileOnly project(':common')
                commonJava project(path: ':common', configuration: 'commonJava')
                commonResources project(path: ':common', configuration: 'commonResources')
            }

            tasks.named('compileJava', JavaCompile) {
                dependsOn(configurations.commonJava)
                source(configurations.commonJava)
            }

            processResources {
                dependsOn(configurations.commonResources)
                from(configurations.commonResources)
            }
        }
    }
}
