# Gradle
org.gradle.jvmargs=-Xmx2G

# Project
archives_base_name=biolith-examples
mod_version=3.7.0
maven_group=com.terraformersmc.biolith
#loom.ignoreDependencyLoomVersionValidation=true
enabled_platforms=fabric,forge,neoforge

# Common
java_version=25
minecraft_version=26.2

# Fabric
fabric_api_version=0.157.0+26.2
fabric_loader_version=0.19.3

# Forge
forge_version=65.1.0

# NeoForge
neoforge_version=26.2.0.59

##
## Dependencies
##

# Biolith
biolith_version=3.7.0-alpha.2
