loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
    convertAw2At(tasks.named("jar", Jar), ["biolith_examples.classtweaker"])
}

repositories {
    // for TerraBlender
    maven {
        name = 'MinecraftForge'
        url = 'https://maven.minecraftforge.net/'
    }
}

dependencies {
    forgeUserdev "net.minecraftforge:forge:${rootProject.minecraft_version}-${rootProject.forge_version}:userdev"

    api("com.terraformersmc:biolith-forge:${rootProject.biolith_version}")
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/mods.toml") {
        expand "version": project.version
    }
}
