loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
    convertAw2At(tasks.named("jar", Jar), ["biolith_examples.classtweaker"])
}

repositories {
    maven {
        name = 'NeoForge'
        url = 'https://maven.neoforged.net/releases/'
    }
}

dependencies {
    forgeUserdev "net.neoforged:neoforge:${rootProject.neoforge_version}:userdev"

    api("com.terraformersmc:biolith-neoforge:${rootProject.biolith_version}")
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": project.version
    }
}
